version: "3.7"

services:

  redis:
    restart: always
    ports:
      - '6379:6379'
    image: redis:latest

  app:
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: .
      args:
        RAILS_ENV: $RAILS_ENV
    image: app
    command: ./start.sh
    ports:
      - '3030:3030'
    env_file:
      - '.env'
    volumes:
      - .:/app
      - bundle_path:/bundle

  db:
    image: 'postgres:10.3-alpine'
    ports:
      - '5401:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    image: 'app'
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    env_file:
      - '.env'

volumes:
  bundle_path:
  postgres:
